### ISSUE TITLE
Can't build on Allegro CL

### ISSUE THREAD

**Issue by macdavid313** [mmaul/clml#11]
this error has been reported during compiling:

```
Attempt to take the value of the unbound variable
`CLML.STATISTICS.RAND::W'.
```

**Comment by mmaul** [comment]
I have been able to obtain Allegro 10 x86_64 and have fixed issues and verified tests run clean. Can you try confirm, that the issue is resolved?

**Comment by mmaul** [comment]
Closing, fixed
