### ISSUE TITLE
Doesn't build on bleeding-edge SBCL

### ISSUE THREAD

**Issue by quicklisp** [mmaul/clml#12]
I got this analysis from Stas Boukarev:

>A failure in clml is caused by

    (deftype dvec () '(simple-array double-float (*)))

> then SVM-INIT does

    (make-array (list n n) :initial-element 0.0d0 :element-type 'double-float)

> And SVM declares that as DVEC, which is clearly mismatching.

**Comment by mmaul** [comment]
Fixed in commit d273027b6a96220e13613a2700700cdc365938e8
