### ISSUE TITLE
datafile.csv referenced in README.md doesn't exist in sample directory...

### ISSUE THREAD

**Issue by neuronsong** [mmaul/clml#25]
In the Sample Data section... the referenced file just doesn't exist.  Other files load just fine.

CL-USER 1 > (ql:quickload :clml)
To load "clml":
  Load 1 ASDF system:
    clml
; Loading "clml"
..
(:CLML)

CL-USER 2 > (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/datafile.csv")
NIL

CL-USER 3 > (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/bc.train.csv")
"/Users/patrick/quicklisp/dists/quicklisp/software/clml-20170403-git/sample/mmaul.github.io/clml.data/sample/bc.train.csv"

**Comment by mmaul** [comment]
Fixed in 25-datafile.csv-referenced-in-README-doesnt-exist the line was actually just an "example" but changed to point at an actual file airquality.csv
