### ISSUE TITLE
Cannot load with latest SBCL

### ISSUE THREAD

**Issue by anquegi** [mmaul/clml#29]
loading clml with latest quicklisp and latest clml, gives the following error:

```
CL-USER> (ql:quickload :clml)
To load "clml":
  Load 1 ASDF system:
    clml
; Loading "clml"
.......

; file: /Users/toni/.roswell/lisp/quicklisp/dists/quicklisp/software/clml-20170630-git/time-series/src/ts-anomaly-detection.lisp
; in: DEFGENERIC E-SCORES
;     (T CLML.TIME-SERIES.ANOMALY-DETECTION::R)
; 
; caught ERROR:
;   (during macroexpansion of (DEFGENERIC E-SCORES
;       ...))
;   COMMON-LISP:T names a defined constant, and cannot be used in
;   a generic function lambda list.
;   See also:
;     The ANSI Standard, Section 3.4.2
........; 
        ; compilation unit aborted
        ;   caught 2 fatal ERROR conditions
        ;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1009CB7913}>.
```

i'm using:
```
CL-USER> (lisp-implementation-type)
"SBCL"
CL-USER> (lisp-implementation-version)
"1.3.20"
```

it seems due to[ this update](http://www.sbcl.org/news.html#1.3.20)

> minor incompatible change: DEF{GENERIC,METHOD} no longer accept some illegal lambda lists such as (defgeneric bar (foo &key foo)) or (defgeneric baz (t)) that were accepted before.

**Comment by anquegi** [comment]
Is the quicklisp version on new releases it works, froked the repo an load as local-project, and it works so this [commit](https://github.com/mmaul/clml/commit/18115f4e493913e7a18835da08bd5cc7aa5158b3) corrected this

**Comment by mmaul** [comment]
Thanks for reporting, and glad it didn't inconvenience you for long :)
